package decthings:model@0.1.0;

interface model-callbacks {
    resource data-loader {
        read: func(
            start-index: u32,
            amount: u32
        ) -> list<list<u8>>;

        shuffle: func(others: list<borrow<data-loader>>);
    }

    resource weights-provider {
        provide: func(data: list<tuple<string, list<u8>>>);
    }

    resource weights-loader {
        read: func() -> list<u8>;
    }

    resource train-tracker {
        is-cancelled: func() -> bool;

        progress: func(progress: f32);

        metrics: func(metrics: list<tuple<string, list<u8>>>);
    }
}

interface model {
    use model-callbacks.{data-loader, weights-provider, weights-loader, train-tracker};

    record param {
        name: string,
        amount: u32,
        total-byte-size: u64,
        data-loader: data-loader,
    }

    record weight-key {
        key: string,
        byte-size: u64,
        weights-loader: weights-loader,
    }

    record other-model-with-weights {
        model-id: string,
        mount-path: string,
        weights: list<weight-key>,
    }

    record initialize-weights-options {
        params: list<param>,
        weights-provider: weights-provider,
        other-models: list<other-model-with-weights>,
    }

    initialize-weights: func(options: initialize-weights-options) -> result<_, string>;

    record other-model {
        model-id: string,
        mount-path: string,
    }

    record instantiate-model-options {
        weights: list<weight-key>,
        other-models: list<other-model>,
    }

    enum decthings-element-type {
        %f32,
        %f64,
        i8,
        i16,
        i32,
        i64,
        %u8,
        %u16,
        %u32,
        %u64,
        %string,
        boolean,
        binary,
        image,
        audio,
        video,
    }

    record decthings-tensor-rules {
        shape: list<option<u32>>,
        allowed-types: list<decthings-element-type>,
    }

    record decthings-parameter-definition {
        name: string,
        required: bool,
        rules: decthings-tensor-rules,
    }

    record evaluate-options {
        params: list<param>,
        expected-output-types: list<decthings-parameter-definition>,
    }

    record evaluate-output {
        name: string,
        data: list<list<u8>>,
    }

    record train-options {
        params: list<param>,
        tracker: train-tracker,
    }

    record get-weights-options {
        weights-provider: weights-provider,
    }

    resource instantiated {
        evaluate: func(options: evaluate-options) -> result<list<evaluate-output>, string>;
        train: func(options: train-options) -> result<_, string>;
        get-weights: func(options: get-weights-options) -> result<_, string>;
    }

    instantiate-model: func(options: instantiate-model-options) -> result<instantiated, string>;
}

world model-runner {
    import model-callbacks;
    export model;
}
