[package]
name = "decthings-model-tests"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
decthings-model = { path = "../" }
wit-bindgen-rt = "0.26"

[package.metadata.component]
package = "decthings:model"
